//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        public int idCuenta { get; set; }
        public string cbu { get; set; }
        public string alias { get; set; }
        public Nullable<decimal> saldoPesos { get; set; }
        public Nullable<decimal> saldoDolares { get; set; }
        public string cvu { get; set; }
        public int idCliente { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
