//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operaciones
    {
        public int idOperacion { get; set; }
        public string nombreOperacion { get; set; }
        public Nullable<decimal> montoPesos { get; set; }
        public Nullable<System.DateTime> tiempoPlazo { get; set; }
        public string destino { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<decimal> montoDolares { get; set; }
        public int idCuenta { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
    }
}
