//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularMVCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operaciones
    {
        public int idOperacion { get; set; }
        public string nombreOperacion { get; set; }
        public Nullable<decimal> montoPesos { get; set; }
        public string destino { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<decimal> montoDolares { get; set; }
        public int idCuenta { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
    }
}
